controllers:
    resource: '../src/Controller/'
    type: attribute

register:
    path: /register
    controller: App\Controller\UserController::createUser
    methods: ['POST', 'GET']

api_confirm_email:
    path: /api/confirmemail
    controller: App\Controller\MainController::confirmEmail

api_login_check:
    path: /api/login_check